---
# This playbook is used to attribute roles

- hosts: oci
  tasks:
    - include_tasks: roles/setup/tasks/oci.yml
    - include_tasks: roles/reboot/tasks/oci.yml
    - include_tasks: roles/stop/tasks/oci.yml
    - include_tasks: roles/start/tasks/oci.yml

- hosts: proxmox
  tasks:
    - import_tasks: roles/setup/tasks/proxmox.yml
    - import_tasks: roles/start/tasks/proxmox.yml
