---
# This playbook is used to restart container from docker host
- name: Restart Container
  community.docker.docker_container:
    name: "{{ item }}"
    restart: yes
    state: started
  loop: "{{ container_ids }}"
  tags:
    - reboot
