---
# This playbook is used to reboot proxmox host
- name: Reboot Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    api_host: '{{ lookup("env", "PROXMOX_URL") }}'
    api_user: '{{ lookup("env", "PROXMOX_USER") }}'
    api_token_id: '{{ lookup("env", "PROXMOX_TOKEN_ID") }}'
    api_token_secret: '{{ lookup("env", "PROXMOX_TOKEN_SECRET") }}'
    state: restarted
    timeout: 90
    validate_certs: false
    unprivileged: true
  loop: "{{ proxmox_vmids }}"
  tags:
    - reboot
  delegate_to: localhost
