---
# This playbook is used to stop proxmox host
- name: Stop Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    api_host: '{{ lookup("env", "PROXMOX_URL") }}'
    api_user: '{{ lookup("env", "PROXMOX_USER") }}'
    api_token_id: '{{ lookup("env", "PROXMOX_TOKEN_ID") }}'
    api_token_secret: '{{ lookup("env", "PROXMOX_TOKEN_SECRET") }}'
    state: stopped
    timeout: 90
    validate_certs: false
    unprivileged: true
  loop: "{{ proxmox_vmids }}"
  tags:
    - stop
  delegate_to: localhost
