---
# This playbook is used to start container from docker host
- name: Start Container
  community.docker.docker_container:
    name: "{{ item }}"
    state: started
  loop: "{{ container_ids }}"
  tags:
    - start
