---
# This playbook is used to start proxmox host
- name: Show proxmox_vmids
  debug:
    var: proxmox_vmids
  tags:
    - start
  delegate_to: localhost

- name: Start Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    api_host: '{{ lookup("env", "PROXMOX_URL") }}'
    api_user: '{{ lookup("env", "PROXMOX_USER") }}'
    state: started
    timeout: 90
  loop: "{{ proxmox_vmids }}"
  tags:
    - start
  delegate_to: localhost
