---
# This playbook is used to start proxmox host
- name: Start Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    api_host: '{{ lookup("env", "PROXMOX_URL") }}'
    api_user: '{{ lookup("env", "PROXMOX_USER") }}'
    api_token_id: '{{ lookup("env", "PROXMOX_TOKEN_ID") }}'
    api_token_secret: '{{ lookup("env", "PROXMOX_TOKEN_SECRET") }}'
    state: started
    timeout: 90
  loop: "{{ proxmox_vmids }}"
  tags:
    - start
  delegate_to: localhost
