---
# This playbook is used to start proxmox host
- name: Show proxmox_vmids
  debug:
    msg: "{{ item }}"
  loop: "{{ proxmox_vmids }}"
  delegate_to: localhost

- name: Start Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    state: started
    timeout: 90
  loop: "{{ proxmox_vmids }}"
  delegate_to: localhost
