---
# This playbook is used to start proxmox host
- name: Show proxmox_vmids
  debug:
    var: item

- name: Start Proxmox host
  community.general.proxmox:
    vmid: "{{ item }}"
    state: started
    timeout: 90
